Repository Platzi-Master-C8/gethired-jobplacement-enterprise-Frontend, pull requests merged in 2022-03, with the labels that each got.

#91 fix: react router link to postulants view
  src/components/CardApplicantList/CardApplicantList.jsx
Labels: bug

#90 fix: fetching vacancies by user
  src/api/Vacancies/getVacanciesByUser.js
  src/components/ListOfVacancies/index.jsx
  src/components/NoVacanciesCreated/index.jsx
Labels: vacancies flow

#92 Feature/30 Applicant view changes, include data from the API
  src/api/Applicant/getApplicantByVacancy.js
  src/api/Vacancies/getVacancyById.js
  src/components/ApplicantComparison/index.jsx
  src/components/CardApplicantList/CardApplicantList.jsx
  src/components/CardNoApplicant/index.jsx
  src/components/OfferDetails/index.jsx
  src/components/Vacancy/index.jsx
  src/pages/ListCandidatesVacancies.jsx
Labels: vacancies flow

#94 feat: public component in non-logged header
  package.json
  src/components/Header/index.jsx
Labels: enhancement

#96 feat: added favicon
  public/favicon-144.png
  public/favicon-144.png:Zone.Identifier
  public/favicon-64.png
  public/favicon-64.png:Zone.Identifier
  public/index.html
Labels: enhancement

#101 fix: company details redirection
  src/components/JobDetailsModal/index.jsx
Labels: user's flow

#103 fix: header display on mobile
  package.json
Labels: bug

#99 Bug 97/applicants by vacancy errors
  package.json
  src/api/Vacancies/getVacancyById.js
  src/components/ApplicantComparison/index.jsx
  src/components/CardApplicantList/CardApplicant.jsx
  src/components/CardApplicantList/CardApplicantSkeleton.jsx
  src/components/CardApplicantList/index.jsx
  src/components/Commons/TableSkeleton/index.jsx
  src/components/JobOffers/workspace.code-workspace
  src/components/NewApplicants/index.jsx
  src/components/NewVacancies/index.jsx
  src/components/OfferDetails/OfferDetailsSkeleton.jsx
  src/components/OfferDetails/index.jsx
  src/components/OtherPostulations/index.jsx
  src/components/PostulationKanban/KanbanColumn.jsx
  src/components/RecruitmentProcess/index.jsx
  src/pages/ListCandidatesVacancies.jsx
  src/pages/PostulationDetail.jsx
Labels: vacancies flow

#108 Feature 105/postulants kanban
  src/api/Applicants/getApplicantByVacancy.js
  src/components/ApplicantComparison/index.jsx
  src/components/CardApplicantList/CardApplicant.jsx
  src/components/PostulationKanban/KanbanColumn.jsx
  src/components/PostulationKanban/data.js
  src/pages/ListCandidatesVacancies.jsx
  src/routes/index.jsx
Labels: postulation flow

#106 Feature 33
  src/api/Applicant/getApplicantById.js
  src/api/Interviews/cancelInterview.js
  src/api/Interviews/getAllInterviews.js
  src/api/Interviews/rescheduleInterview.js
  src/components/InterviewCard/index.jsx
  src/components/Interviews/InterviewCancelModal.jsx
  src/components/Interviews/InterviewCard.jsx
  src/components/Interviews/InterviewCardSkeleton.jsx
  src/components/Interviews/InterviewRescheduleModal.jsx
  src/components/Interviews/InterviewsList.jsx
  src/components/Interviews/index.jsx
  src/components/Layout.jsx
  src/pages/Interviews.jsx
  src/pages/InterviewsDashboard.jsx
  src/pages/Theme.jsx
  src/routes/index.jsx
Labels: enhancement

#111 Readme
  readme.md
Labels: enhancement
