Repository Platzi-Master-C8/gethired-jobplacement-enterprise-Frontend, pull requests merged in 2022-02, with the labels that each got.

#43 Bug Report #24 - vacancy creation redirect on submit
  src/components/FormVacancies/FormVacancies.jsx
  src/pages/CreateVacancies.jsx
Labels: enhancement

#40 Bug Report - fix header display and responsiveness #22
  package.json
  src/components/Header/HeaderDesktop.jsx
  src/components/Header/HeaderMobile.jsx
  src/components/Header/header.jsx
  src/components/Header/index.jsx
  src/components/Layout.jsx
  src/components/ListOfVacancies/styles.js
  src/pages/VacanciesHistory.jsx
  src/style/header.scss
Labels: header

#46 Feat 45: create modal code
  src/components/ModalCode/index.jsx
  src/pages/Offers.jsx
  src/routes/index.jsx
  yarn.lock
Labels: enhancement

#49 Feature 47 - Home page users
  .eslintrc.js
  src/api/Vacancies/allVacancies.js
  src/components/FiltersUsers/FiltersUsers.jsx
  src/components/FiltersUsers/index.js
  src/components/JobOffers/JobCard.jsx
  src/components/JobOffers/JobSkeleton.jsx
  src/components/JobOffers/Jobs.jsx
  src/components/JobOffers/helpers.js
  src/components/JobOffers/index.jsx
  src/constants/index.js
  src/hooks/useFetch.js
  src/hooks/usePagination.js
  src/hooks/useSearch.js
  src/pages/Offers.jsx
  src/routes/index.jsx
  src/style/style.scss
  webpack.config.js
Labels: enhancement

#53 Feature 41/home view
  package-lock.json
  package.json
  src/components/ApplicantItemCard/index.jsx
  src/components/FormVacancies/FormVacancies.jsx
  src/components/Header/HeaderDesktop.jsx
  src/components/ListOfVacancies/index.jsx
  src/components/MainScheduler/index.jsx
  src/components/MainStatCard/index.jsx
  src/components/ModalCode/index.jsx
  src/components/NewApplicants/index.jsx
  src/components/NewVacancies/index.jsx
  src/components/Vacancy/index.jsx
  src/components/VacancyItemCard/index.jsx
  src/pages/EnterpriseHome.jsx
  src/pages/Profile.jsx
  src/routes/index.jsx
  yarn.lock
Labels: enhancement

#56 feat: table pagination component
  src/components/TablePagination/index.jsx
Labels: dashboard

#57 fix: routes refactor
  src/components/CardApplicantList/CardApplicantList.jsx
  src/components/Vacancy/index.jsx
  src/routes/index.jsx
Labels: enhancement

#61 refactor: set users home page as main for status notlogged
  src/routes/index.jsx
Labels: user's flow

#58 Feature 51 - Create the job offer detail modal
  package-lock.json
  package.json
  src/components/JobDetailsModal/index.jsx
  src/components/JobOffers/JobCard.jsx
  src/components/JobOffers/Jobs.jsx
  src/components/SkeletonVacancyHistory/index.jsx
  src/pages/Offers.jsx
  yarn.lock
Labels: enhancement, user's flow

#68 Feature 54/postulation user view
  package.json
  src/components/ApplicantComparison/index.jsx
  src/components/CardApplicantList/CardApplicantList.jsx
  src/components/CardApplicantList/styles.js
  src/components/OfferDetails/index.jsx
  src/components/OtherPostulations/index.jsx
  src/components/RecruitmentProcess/helpers.js
  src/components/RecruitmentProcess/index.jsx
  src/components/TableStyling/index.jsx
  src/pages/ListCandidatesVacancies.jsx
  src/pages/PostulationDetail.jsx
  src/routes/index.jsx
Labels: postulation flow

#70 Feature 69 - modal vancacy
  src/api/Vacancies/stateVacancy.js
  src/components/FiltersUsers/FiltersUsers.jsx
  src/components/JobDetailsModal/index.jsx
  src/components/JobOffers/JobCard.jsx
  src/components/JobOffers/Jobs.jsx
  src/components/JobOffers/helpers.js
  src/components/ModalCode/index.jsx
  src/hooks/useFetch.js
Labels: enhancement

#73 Feature 25 - Vacancies skills
  src/api/TypesOfWork/getAllTypesOfWork.js
  src/api/Vacancies/getVacancyById.js
  src/api/Vacancies/postNewVacancy.js
  src/api/Vacancies/updateVacancy.js
  src/api/axiosClient.js
  src/components/Commons/InputText/index.jsx
  src/components/Commons/Tags/index.jsx
  src/components/FormVacancies/index.jsx
Labels: enhancement

#76 Merge develop in release branch
  .github/workflows/deploy.yml
  package.json
  src/api/TypesOfWork/getAllTypesOfWork.js
  src/api/Vacancies/getVacancyById.js
  src/api/Vacancies/postNewVacancy.js
  src/api/Vacancies/stateVacancy.js
  src/api/Vacancies/updateVacancy.js
  src/api/axiosClient.js
  src/components/ApplicantComparison/index.jsx
  src/components/CardApplicantList/CardApplicantList.jsx
  src/components/CardApplicantList/styles.js
  src/components/Commons/InputText/index.jsx
  src/components/Commons/Tags/index.jsx
  src/components/FiltersUsers/FiltersUsers.jsx
  src/components/FormVacancies/index.jsx
  src/components/JobDetailsModal/index.jsx
  src/components/JobOffers/JobCard.jsx
  src/components/JobOffers/Jobs.jsx
  src/components/JobOffers/helpers.js
  src/components/ModalCode/index.jsx
  src/components/OfferDetails/index.jsx
  src/components/OtherPostulations/index.jsx
  src/components/RecruitmentProcess/helpers.js
  src/components/RecruitmentProcess/index.jsx
  src/components/TableStyling/index.jsx
  src/hooks/useFetch.js
  src/pages/ListCandidatesVacancies.jsx
  src/pages/PostulationDetail.jsx
  src/routes/index.jsx
  webpack.config.js
Labels: enhancement

#80 Feature 55/postulation tracking
  src/components/CardApplicantList/CardApplicantList.jsx
  src/components/CardApplicantList/styles.js
  src/components/PostulationKanban/KanbanColumn.jsx
  src/components/PostulationKanban/data.js
  src/components/PostulationKanban/index.jsx
  src/pages/ListCandidatesVacancies.jsx
  src/pages/PostulationDetail.jsx
  src/pages/Postulations.jsx
  src/routes/index.jsx
Labels: postulation flow

#81 Feature 74: add filters
  src/api/Filters/getFilters.js
  src/api/Vacancies/allActiveVacancies.js
  src/components/FiltersUsers/FiltersUsers.jsx
  src/components/JobDetailsModal/index.jsx
  src/components/JobOffers/Jobs.jsx
  src/components/JobOffers/index.jsx
  src/hooks/useFetch.js
Labels: enhancement
